server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/auth/**
  security:
    oauth2:
      resourceserver:
        jwt: 
          secret-key: ${JWT_SECRET}

# For local development, you can set a default value for JWT_SECRET here:
JWT_SECRET: mysupersecurejwtsecretkeyforflight2026project